/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Entidades.Combos;
import Entidades.HistorialPrecio;
import Entidades.Porcentaje;
import Entidades.Producto;
import Entidades.Promocion;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author alan
 */
public final class ModificarProducto extends javax.swing.JDialog {
    
    private Producto productoMod = new Producto();
    private boolean modificado = false;
    
    
    public boolean precioModificado(){
        return modificado;
    }
    /**
     * Creates new form ModificarProducto
     * @param parent
     * @param modal
     */
    public ModificarProducto(java.awt.Frame parent, boolean modal , Producto prod) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.DARK_GRAY);
        cargarBoxDescuento();
        actualizar(prod);
        productoMod.setPrecio(prod.getPrecio());
        productoMod.setCodigo(prod.getCodigo());
    }
    
    private void actualizar(Producto p){
        descripcion.setText(p.getNombre());
        stock.setText(Integer.toString(p.getStock()));
        precio.setText(Double.toString(p.getPrecio()));
    }
    
    private void cargarBoxDescuento(){
        DescuentoBox.removeAllItems();
        DescuentoBox.addItem("Ninguno");
        DescuentoBox.addItem("Combo 3x2");
        DescuentoBox.addItem("Combo 8x6");
        DescuentoBox.addItem("25%");
        DescuentoBox.addItem("15%");
        DescuentoBox.addItem("10%");
        DescuentoBox.addItem("5%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modificar = new javax.swing.JButton();
        precio = new javax.swing.JTextField();
        descripcion = new javax.swing.JTextField();
        stock = new javax.swing.JTextField();
        DescuentoBox = new javax.swing.JComboBox<>();
        cancelarBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificar.setText("MODIFICAR");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 150, -1));

        precio.setBackground(new java.awt.Color(0, 0, 0));
        precio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        precio.setForeground(new java.awt.Color(255, 255, 255));
        precio.setCaretColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 180, 30));

        descripcion.setBackground(new java.awt.Color(0, 0, 0));
        descripcion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        descripcion.setForeground(new java.awt.Color(255, 255, 255));
        descripcion.setCaretColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 180, 30));

        stock.setBackground(new java.awt.Color(0, 0, 0));
        stock.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        stock.setForeground(new java.awt.Color(255, 255, 255));
        stock.setCaretColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 180, 30));

        DescuentoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DescuentoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescuentoBoxActionPerformed(evt);
            }
        });
        getContentPane().add(DescuentoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 140, 30));

        cancelarBtn.setText("CANCELAR");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 150, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DESCRIPCION");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NUEVO STOCK");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NUEVO PRECIO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TIPO DE DESCUENTO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 30));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NUEVA VENTA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 330, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean modoficacionRealizada (){
        return modificado;
    }
    
    private void actualizarArchivo(){
        ArrayList<Producto> listaArch = Seguridad.Archivo.listaProducto();
        String outputFile = "test/archivo_producto.csv";
        File ficheroProducto = new File(outputFile);
        ficheroProducto.delete();
        Seguridad.Archivo.inicializarProducto(); 
        for (Producto aux : listaArch){ 
            if (aux.getCodigo() == productoMod.getCodigo()){
                Seguridad.Archivo.nuevoProducto(productoMod);
            }
            else{
                Seguridad.Archivo.nuevoProducto(aux);
            }
        }
    }
    
    
    private void DescuentoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescuentoBoxActionPerformed
        //nada
    }//GEN-LAST:event_DescuentoBoxActionPerformed

    
    private String error(){
        String errorCampos = "";
        if (descripcion.getText().equals("")){
            errorCampos +="error en el nombre.";      
        }
        try {
            Integer.parseInt(stock.getText());
        }  
        catch(NumberFormatException ex){
            errorCampos += "El stock acepta valores numericos.";
        }
        try {
            Double.parseDouble(precio.getText());
        }  
        catch(NumberFormatException ex){
            errorCampos += " El precio aceptan valores numericos.";
        }
        return errorCampos;
    }
    
    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        String mensajeError = error() ;
        if ((mensajeError!= "")){
            Error error = new Error(new javax.swing.JFrame(),true, mensajeError);
            error.setVisible(true);
        }
        else{
            modificado = true;
            productoMod.setNombre(descripcion.getText());
            if (productoMod.getPrecio() != Double.parseDouble(precio.getText())){
                Seguridad.Archivo.nuevoPrecioHistorial(new HistorialPrecio(Integer.toString(productoMod.getCodigo()), productoMod.getPrecio()));
                productoMod.setPrecio(Double.parseDouble(precio.getText()));
            }
            productoMod.setStock(Integer.parseInt(stock.getText()));
            productoMod.setTipoPromocion(DescuentoBox.getItemAt(DescuentoBox.getSelectedIndex()));
            actualizarArchivo();
            setVisible(false);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DescuentoBox;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JTextField descripcion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField stock;
    // End of variables declaration//GEN-END:variables
}
